package com.coffeeshop.enums;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    ORDER_CANCELLED,
    ORDER_COMPLETED,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLED,
    RESERVATION_REMINDER,
    TABLE_AVAILABLE,
    SYSTEM_ANNOUNCEMENT
}